baseURL = "https://pinterlude.com/"
languageCode = "en"
title = "Pinterlude"

[params]
  tagline = "The interlude between two lives"
  description = "The journal of a radical life choice — by Marc & Linda"
